---
language: rust
rust:
    - nightly
sudo: true
cache:
  - apt
  - cargo

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          packages:
            - libpcap-dev
      env: TARGET=i686-unknown-linux-gnu

before_script:
  - cargo +nightly install
  #- cargo +nightly install --force rustfmt-nightly

script:
  - export PATH="/usr/include:$PATH"
  #- cargo +nightly fmt --all -- --check
  - cargo test
  - cargo doc --no-deps

notifications:
  email:
    on_success: never

